<!DOCTYPE html>
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="/assets/favicon.ico">
        <title>Public Library</title>
        <link href="/assets/bootstrap.min.css" rel="stylesheet">
        <link href="/assets/justified-nav.css" rel="stylesheet">
    </head>
    <body>

        <div class="container">

            <div class="masthead">
                <h3 class="text-muted">Library</h3>
                <ul class="nav nav-justified">
                    <li><a href="/admin">Admin Home</a></li>
                    <li><a href="/admin/checkin">Check In</a></li>
                    <li><a href="/admin/checkout">Check Out</a></li>
                    <li class="active"><a href="/admin/addbook">Add Book</a></li>
                    <li><a href="/logout">Logout</a></li>
                </ul>
            </div>
            <h2 class="text-center">Add Books</h2>
            <?php
            $flashes = $this->flashes();
            if (count($flashes) > 0) {
                echo '<div class="row">';
                foreach ($flashes as $type => $messages):
                    foreach ($messages as $msg):
                        echo '<h5 class="alert alert-danger">' . $msg . '</h5>';
                    endforeach;
                endforeach;
                echo '</div>';
            }
            ?>
            <div class="row">
                <div class="col-lg-1"></div>
                <div class="col-lg-4">
                    <h2>Existing Book</h2>
                    <form class="form-register" method="post" action="/admin/addbook" role="form">
                        <input hidden name="new" value="false">
                        ISBN: <input input name="isbn" type="text" class="form-control" placeholder="ISBN"><p></p>
                        Quantity: <input input name="quantity" type="number" class="form-control" placeholder="Quantity"><br>
                        <p align="center">
                            <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
                        </p>
                        <br>
                    </form>
                </div>
                <div class="col-lg-2"></div>
                <div class="col-lg-4">
                    <h2>New Book</h2>
                    <form class="form-register" role="form" method="post" action="/admin/addbook">
                        <input hidden name="new" value="true">
                        Title:<input name="title" type="text" class="form-control" placeholder="Title" required><p></p>
                        ISBN: <input name ="isbn" type ="text" class ="form-control" placeholder ="ISBN" required><p></p>
                        Author: <input name="author" type="text" class="form-control" placeholder="Author"><p></p>
                        Genre: <input name = "genres" type = "text" class = "form-control" placeholder = "Genre" required>
                        Quantity: <input input name="quantity" type="number" class="form-control" placeholder="Quantity"><br>
                        Description: <textarea id="desc" name="desc" class="form-control"></textarea>
                        <br><br>
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
                    </form>
                </div>
                <div class="col-lg-1"></div>
            </div>

            <div class="footer">
                <p>© AE97 2014</p>
            </div>

        </div>

        <script src="/assets/ie10-viewport-bug-workaround.js"></script>

    </body>
</html>
