<!DOCTYPE html>
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="/assets/favicon.ico">
        <title>Public Library</title>
        <link href="/assets/bootstrap.min.css" rel="stylesheet">
        <link href="/assets/justified-nav.css" rel="stylesheet">
    </head>

    <body>

        <div class="container">

            <div class="masthead">
                <h3 class="text-muted">Library</h3>
                <ul class="nav nav-justified">
                    <li><a href="/home">Home</a></li>
                    <li><a href="/search">Search</a></li>
                    <li><a href="/about">About</a></li>
                    <li><a href="/contact">Contact</a></li>
                    <?php
                    if (isLoggedIn()) {
                        echo '<li><a href="/logout">Logout</a></li>';
                    } else {
                        echo '<li><a href="/login">Login</a></li>';
                    }
                    ?>
                </ul>
            </div>
            <?php if (isLoggedIn()) { ?>
            <div class="masthead">
                    <ul class="nav nav-justified">
                        <li><a href="/watchlist">Watchlist</a></li>
                        <li><a href="/payment">Payment</a></li>
                        <li><a href="/settings">Account Settings</a></li>
                    </ul>
                </div>
            <?php }
            ?>

            <div class="row">
                <div class="col-lg-4"></div>
                <div class="col-lg-4">
                    <h2 align="center">Book</h2>
                    <p><strong>Title:</strong> <?php echo $this->book['title']; ?></p>
                    <p><strong>Author:</strong> <?php echo $this->book['author']; ?></p>
                    <p><strong>Description:</strong> <?php echo $this->book['desc']; ?></p>
                    <strong>Genre: </strong><br>
                    <?php if (isLoggedIn()) { ?>
                            <p align="center"><a class="btn btn-primary" role="button" href="/watchlist-add?isbn=<?php echo $this->book['isbn']; ?>">Add</a>
                                <a class="btn btn-primary" role="button" href="/watchlist-delete?isbn=<?php echo $this->book['isbn']; ?>">Remove</a>
                                </p>
                    <?php } ?>
                </div>
            </div>



            <div class="footer">
                <p>© AE97 2014</p>
            </div>

        </div>

        <script src="./assets/ie10-viewport-bug-workaround.js"></script>

    </body>
</html>
