<!DOCTYPE html>
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="/assets/favicon.ico">
        <title>Public Library</title>
        <link href="/assets/bootstrap.min.css" rel="stylesheet">
        <link href="/assets/justified-nav.css" rel="stylesheet">
    </head>

    <body>

        <div class="container">

            <div class="masthead">
                <h3 class="text-muted">Library</h3>
                <ul class="nav nav-justified">
                    <li class="active"><a href="/home">Home</a></li>
                    <li><a href="/search">Search</a></li>
                    <li><a href="/about">About</a></li>
                    <li><a href="/">Contact</a></li>
                    <?php
                    if (isLoggedIn()) {
                        echo '<li><a href="/logout">Logout</a></li>';
                    } else {
                        echo '<li><a href="/login">Login</a></li>';
                    }
                    ?>
                </ul>
            </div>
            <?php if (isLoggedIn()) { ?>
                <div class="masthead">
                    <ul class="nav nav-justified">
                        <li><a href="/watchlist">Watchlist</a></li>
                        <li><a href="/payment">Payment</a></li>
                        <li><a href="/bookview">Book view</a></li>
                        <li><a href="/settings">Account Settings</a></li>
                    </ul>
                </div>
                <?php }
                ?>

                <div class="jumbotron">
                    <h2>Welcome to the Public Library website!</h2>
                    <p><a class="btn btn-lg btn-success" href="/search" role="button">Look for a book today</a></p>
                </div>

                <div class="row">
                    <div class="col-lg-4">
                        <h2>Search</h2>
                        <p>Find books by searching for the title, author, or ISBN number. If you find a book you can add it to your watchlist for later check-out.</p>

                    </div>
                    <div class="col-lg-4">
                        <h2>Great Reads</h2>
                        <p><strong>Title:</strong> <?php echo $this->randomBook['title']; ?></p>
                        <p><strong>Author:</strong> <?php echo $this->randomBook['author']; ?></p>
                        <p><strong>Description:</strong> <?php echo $this->randomBook['desc']; ?></p>
                </div>

                <div class="col-lg-4">
                    <h2>Contact Us</h2>
                    <p>If you have any questions about our library or if you need help with your user account feel free to contact us. </p>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-4">
                    <p><a class="btn btn-primary" href="/search" role="button">Search »</a></p>
                </div>
                <div class="col-lg-4">
                    <p><a class="btn btn-primary" href="#" role="button">View Book »</a></p>
                </div>
                <div class="col-lg-4">
                    <p><a class="btn btn-primary" href="/contact" role="button">Contact Us »</a></p>
                </div>
            </div>


            <div class="footer">
                <p>© AE97 2014</p>
            </div>

        </div>

        <script src="./assets/ie10-viewport-bug-workaround.js"></script>

    </body>
</html>
