<!DOCTYPE html>
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="/assets/favicon.ico">
        <title>Public Library</title>
        <link href="/assets/bootstrap.min.css" rel="stylesheet">
        <link href="/assets/justified-nav.css" rel="stylesheet">
        <link href="/assets/signin.min.css" rel="stylesheet">
    </head>

    <body>

        <div class="container">

            <div class="masthead">
                <h3 class="text-muted">Library</h3>
                <ul class="nav nav-justified">
                    <li><a href="/home">Home</a></li>
                    <li><a href="/search">Search</a></li>
                    <li><a href="/about">About</a></li>
                    <li><a href="/contact">Contact</a></li>
                    <?php
                    if (isset($_SESSION['email'])) {
                        echo '<li class="active"><a href="/logout">Logout</a></li>';
                    } else {
                        echo '<li class="active"><a href="/login">Login</a></li>';
                    }
                    ?>
                </ul>
            </div>


            <div class="row">

            </div>

            <div class="row">
                <div class="col-lg-4">
                </div>
                <div class="col-lg-4">                    
                    <form class = "form-signin" role = "form" action = "/login" method = "post">
                        <?php
                        foreach ($this->flashes() as $type => $messages):
                            foreach ($messages as $msg):
                                echo '<h5 class="alert alert-danger">' . $msg . '</h5>';
                            endforeach;
                        endforeach;
                        ?>
                        <h3 class = "form-signin-heading">Login</h3>
                        <input name = "email" type = "text" class = "form-control" placeholder = "Email" required autofocus>
                        <input name = "password" type = "password" class = "form-control" placeholder = "Password" required>
                        <button class = "btn btn-block" type = "submit">Login</button>
                        <p></p>
                        <p><a href='/resetpassword'>Forgot password</a></p>
                        <p><a href='/register'>Register</a></p>
                    </form>
                </div>
                <div class="col-lg-4">
                </div>
            </div>

            <div class="footer">
                <p>© AE97 2014</p>
            </div>

        </div>

        <script src="/assets/ie10-viewport-bug-workaround.js"></script>

    </body>
</html>
