<!DOCTYPE html>
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="/assets/favicon.ico">
        <title>Public Library</title>
        <link href="/assets/bootstrap.min.css" rel="stylesheet">
        <link href="/assets/justified-nav.css" rel="stylesheet">
    </head>

    <body>

        <div class="container">

            <div class="masthead">
                <h3 class="text-muted">Library</h3>
                <ul class="nav nav-justified">
                    <li><a href="/home">Home</a></li>
                    <li><a href="/search">Search</a></li>
                    <li><a href="/about">About</a></li>
                    <li><a href="/">Contact</a></li>
                    <?php
                    if (isLoggedIn()) {
                        echo '<li><a href="/logout">Logout</a></li>';
                    } else {
                        echo '<li><a href="/login">Login</a></li>';
                    }
                    ?>
                </ul>
            </div>
            <?php if (isLoggedIn()) { ?>
            <div class="masthead">
                    <ul class="nav nav-justified">
                        <li><a href="/watchlist">Watchlist</a></li>
                        <li class="active"><a href="/payment">Payment</a></li>
                        <li><a href="/settings">Account Settings</a></li>
                    </ul>
                </div>
            <?php }
            ?>
            <div class="row">
                <div class="col-lg-8"></div>
                <div class="col-lg-3"><h2><strong>Total:</strong> $<?php echo $this->total; ?></h2></div>
                <div class="col-lg-1"><h2><button class="btn btn-success" onclick="paymentPopup()">Pay</button></h2></div>
            </div>
                <div class="row">
                    <table class="table table-striped ">
                        <thead>
                            <tr>
                                <th id="title_column" style ="width:20%">Transaction ID</th>
                                <th id="title_genre" style ="width:20%">Date</th>
                                <th id="title_genre" style ="width:20%">Total</th>
                                <th id="title_isbn" style ="width:40%">Description</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($this->history as $payment) { ?>
                                <tr>
                                    <td><p><?php echo $payment['id']; ?></p></td>
                                    <td><p><?php echo $payment['date']; ?></p></td>
                                    <td><p><?php echo $payment['payment']; ?></p></td>
                                    <td><p><?php echo $payment['description']; ?></p></td>
                                </tr>
                            <?php } ?>
                    </tbody>              
                </table>
            </div>

            <div class="footer">
                <p>© AE97 2014</p>
            </div>

        </div>

        <script type="text/javascript">
            function paymentPopup() {
                newwindow=window.open('pay?total=<?php echo $this->total;?>', 'Pay fees', 'height=200,width=200');
                if(window.focus) {
                    newwindow.focus();
                }
            }
        </script>

        <script src="./assets/ie10-viewport-bug-workaround.js"></script>

    </body>
</html>