<!DOCTYPE html>
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="/assets/favicon.ico">
        <title>Public Library</title>
        <link href="/assets/bootstrap.min.css" rel="stylesheet">
        <link href="/assets/justified-nav.css" rel="stylesheet">
        <link href="/assets/signin.min.css" rel="stylesheet">
    </head>

    <body>

        <div class="container">

            <div class="masthead">
                <h3 class="text-muted">Library</h3>
                <ul class="nav nav-justified">
                    <li><a href="/home">Home</a></li>
                    <li><a href="/search">Search</a></li>
                    <li><a href="/">About</a></li>
                    <li><a href="/">Contact</a></li>
                    <?php
                    if (isset($_SESSION['email'])) {
                        echo '<li class="active"><a href="/logout">Logout</a></li>';
                    } else {
                        echo '<li class="active"><a href="/login">Login</a></li>';
                    }
                    ?>
                </ul>
            </div>

            <div class="row" style="padding-top: 50px; text-align: center;">
                <h3 class = "form-signin-heading">Password reset</h3>
                <p>Please enter your email</p>
                <form class="form-signin" role ="form" action="/resetpassword" method="post">
                    <input name="email" class="form-control" placeholder="example@abc.com" required></input>
                    <p></p>
                    <button type="submit" class="btn btn-success">Reset</button>
                </form>
            </div>

        </div>
    </body>
</html>
