<!DOCTYPE html>
<html lang="en">
    <head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="/assets/favicon.ico">
        <title>Public Library</title>
        <link href="/assets/bootstrap.min.css" rel="stylesheet">
        <link href="/assets/bootstrap-theme.css" rel="stylesheet">
        <link href="/assets/justified-nav.css" rel="stylesheet">
    </head>

    <script src="/assets/jquery.js"></script>
    <script src="/assets/bootstrap.min.js"></script>
    <script src="/assets/knockout.js"></script>
    <script src="/assets/search.js"></script>
    <script type="text/javascript">
        var viewModel = {
            tableLoaded: ko.observable(false),
            bookTable: ko.observableArray()
        };
    </script>

    <body>

        <div class="container">

            <div class="masthead">
                <h3 class="text-muted">Library</h3>
                <ul class="nav nav-justified">
                    <li><a href="/home">Home</a></li>
                    <li class="active"><a href="/search">Search</a></li>
                    <li><a href="/about">About</a></li>
                    <li><a href="#">Contact</a></li>
                    <?php
                    if (isLoggedIn()) {
                        echo '<li><a href="/logout">Logout</a></li>';
                    } else {
                        echo '<li><a href="/login">Login</a></li>';
                    }
                    ?>
                </ul>
            </div>
            
            <?php if (isLoggedIn()) { ?>
                <div class="masthead">
                    <ul class="nav nav-justified">
                        <li><a href="/watchlist">Watchlist</a></li>
                        <li><a href="/fees">Fees</a></li>
                        <li><a href="/bookview">Book view</a></li>
                        <li><a href="/settings">Account Settings</a></li>
                    </ul>
                </div>
                <?php }
                ?>

            <div class="col-lg-12">
                <h3 class="text-center" style="padding-top: 5%">Search for any book, author, genre or ISBN number</h3>
                <div class="input-group">
                    <div class="input-group-btn">
                        <button id="searchTypeButton" value="author" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">Author <span class="caret"></span></button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a id="authorSearchType" class="searchTypeClass" value="author">Author</a></li>
                            <li><a id="isbnSearchType" class="searchTypeClass" value="isbn">ISBN</a></li>
                            <li><a id="titleSearchType" class="searchTypeClass" value="title">Title</a></li>
                        </ul>
                    </div>
                    <input id="query" type="text" class="form-control" required>
                </div>
                <div  class="jumbotron">
                    <button class="btn btn-success" id="searchButton">Search</button>
                </div>
            </div>

            <div class="row">
                <table data-bind="visible: tableLoaded" class="table table-striped">
                    <thead>
                        <tr>
                            <th id="title_column" style ="width:25%">Title</th>
                            <th id="title_genre" style ="width:20%">Author</th>
                            <th id="title_genre" style ="width:50%">Description</th>
                            <th id="title_isbn" style ="width:5%">ISBN</th>
                        </tr>
                    </thead>
                    <tbody data-bind="foreach: bookTable" id="booktable">
                        <tr>
                            <td><p data-bind="html: $data.title"></p></td>
                            <td><p data-bind="text: $data.author"></p></td>
                            <td><p data-bind="html: $data.desc"></p></td>
                            <td><p data-bind="text: $data.isbn"></p></td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="footer">
                <p>© AE97 2014</p>
            </div>

        </div>

        <script src="./assets/ie10-viewport-bug-workaround.js"></script>
        <script type="text/javascript">
        ko.applyBindings(viewModel);
        </script>
    </body>

    <script type="text/javascript">
        $(".searchTypeClass").on('click', function (event) {
            var tag = $("#" + event.target.id);
            $("#searchTypeButton").html(tag.text() + " <span class=\"caret\"></span>");
            $("#searchTypeButton").val(tag.attr("value"));
        });
        $("#searchButton").on('click', function () {
            var type = $("#searchTypeButton").val();
            var query = $("#query").val();
            if (query === null || query.trim() === "") {
                return;
            }
            search(type, query);
        });
    </script>

</html>
