<!DOCTYPE html>
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="/assets/favicon.ico">
        <title>Public Library</title>
        <link href="/assets/bootstrap.min.css" rel="stylesheet">
        <link href="/assets/justified-nav.css" rel="stylesheet">
    </head>

    <body>

        <div class="container">

            <div class="masthead">
                <h3 class="text-muted">Library</h3>
                <ul class="nav nav-justified">
                    <li><a href="#">Home</a></li>
                    <li class="active"><a href="#">Search</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Contact</a></li>
                    <li><a href="/login">Login</a></li>
                </ul>
            </div>

            <div class="jumbotron">
                <h3>Search for any book, author, genre or ISBN number</h3>
                <p class="lead"></p>
                <input name = "search" type = "text" class = "form-control" placeholder = "" required autofocus maxlength="256">
                <h1></h1>
                <button class = "btn btn-xs" type = "submit">Search</button>
                <p></p>
            </div>

            <div class="row">
                <table class = "table table-striped">
                    <thead>
                        <tr>
                            <th id = "title_column" style ="width:30%">Title</th>
                            <th id = "title_author" style ="width:25%">Author</th>
                            <th id = "title_genre" style ="width:25%">Genre</th>
                            <th id = "title_isbn" style ="width:20%">ISBN</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><p data-bind="text: $data.title"></p></td>
                            <td><p data-bind="text: $data.author"></p></td>
                            <td><p data-bind="text: $data.genre"></p></td>
                            <td><p data-bind="value: $data.isbn"></p></td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <div class="footer">
                <p>© AE97 2014</p>
            </div>

        </div>

        <script src="./assets/ie10-viewport-bug-workaround.js"></script>

    </body>
</html>
